version: '3'
services:
    web:
      image: 'twang2218/gitlab-ce-zh'
      restart: always
      container_name: gitlab
      privileged: true #这个属性是赋予docker容器中用户root权限，这样在容器中就可以有操作文件权限了
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://106.58.211.243:7060' # 暴露的url
          # nginx['enable'] = true
          gitlab_rails['gitlab_shell_ssh_port'] = 2222 
          unicorn['port'] = 7060
          #nginx['enable'] = false
          nginx['listen_port'] = 80
          #gitlab_workhorse['listen_network'] = "tcp"
          #gitlab_workhorse['listen_addr'] = "127.0.0.1:8085"
          #nginx['enable'] = false
          #unicorn['port'] = 8088
          #unicorn['listen'] = '127.0.0.1'
      ports:
        - '7060:80'
        - '8443:443'
        - '2222:22'
      volumes:
        - ./config:/etc/gitlab # 挂载的数据券，左边是宿主机右边是容器对应位置
        - ./data:/var/opt/gitlab
        - ./logs:/var/log/gitlab
