version: '3.1'
services:
  nginx:
  #  restart: always
    image: nginx
    container_name: nginx
    ports:
      - 10000:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./wwwroot:/usr/share/nginx/wwwroot
