version: '3'
services:
    redis:
        image: "redis:3.2"
        restart: always
        command: redis-server --requirepass luyanan --appendonly yes
        volumes:
            - ./data:/data #数据文件挂载
        ports:
            - "6379:6379"